/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyReportRouteImport } from './routes/weekly-report'
import { Route as TradeLogRouteImport } from './routes/trade-log'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupLibraryRouteImport } from './routes/setup-library'
import { Route as SetupAdvisorRouteImport } from './routes/setup-advisor'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RiskOfRuinRouteImport } from './routes/risk-of-ruin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GamePlanRouteImport } from './routes/game-plan'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChartAnalyzerRouteImport } from './routes/chart-analyzer'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIdRouteImport } from './routes/news.$id'

const WeeklyReportRoute = WeeklyReportRouteImport.update({
  id: '/weekly-report',
  path: '/weekly-report',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeLogRoute = TradeLogRouteImport.update({
  id: '/trade-log',
  path: '/trade-log',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupLibraryRoute = SetupLibraryRouteImport.update({
  id: '/setup-library',
  path: '/setup-library',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdvisorRoute = SetupAdvisorRouteImport.update({
  id: '/setup-advisor',
  path: '/setup-advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskOfRuinRoute = RiskOfRuinRouteImport.update({
  id: '/risk-of-ruin',
  path: '/risk-of-ruin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlanRoute = GamePlanRouteImport.update({
  id: '/game-plan',
  path: '/game-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartAnalyzerRoute = ChartAnalyzerRouteImport.update({
  id: '/chart-analyzer',
  path: '/chart-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chart-analyzer': typeof ChartAnalyzerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/game-plan': typeof GamePlanRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risk-of-ruin': typeof RiskOfRuinRoute
  '/settings': typeof SettingsRoute
  '/setup-advisor': typeof SetupAdvisorRoute
  '/setup-library': typeof SetupLibraryRoute
  '/signup': typeof SignupRoute
  '/trade-log': typeof TradeLogRoute
  '/weekly-report': typeof WeeklyReportRoute
  '/news/$id': typeof NewsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chart-analyzer': typeof ChartAnalyzerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/game-plan': typeof GamePlanRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risk-of-ruin': typeof RiskOfRuinRoute
  '/settings': typeof SettingsRoute
  '/setup-advisor': typeof SetupAdvisorRoute
  '/setup-library': typeof SetupLibraryRoute
  '/signup': typeof SignupRoute
  '/trade-log': typeof TradeLogRoute
  '/weekly-report': typeof WeeklyReportRoute
  '/news/$id': typeof NewsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/chart-analyzer': typeof ChartAnalyzerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/game-plan': typeof GamePlanRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/risk-of-ruin': typeof RiskOfRuinRoute
  '/settings': typeof SettingsRoute
  '/setup-advisor': typeof SetupAdvisorRoute
  '/setup-library': typeof SetupLibraryRoute
  '/signup': typeof SignupRoute
  '/trade-log': typeof TradeLogRoute
  '/weekly-report': typeof WeeklyReportRoute
  '/news/$id': typeof NewsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/chart-analyzer'
    | '/forgot-password'
    | '/game-plan'
    | '/login'
    | '/news'
    | '/onboarding'
    | '/reset-password'
    | '/risk-of-ruin'
    | '/settings'
    | '/setup-advisor'
    | '/setup-library'
    | '/signup'
    | '/trade-log'
    | '/weekly-report'
    | '/news/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/chart-analyzer'
    | '/forgot-password'
    | '/game-plan'
    | '/login'
    | '/news'
    | '/onboarding'
    | '/reset-password'
    | '/risk-of-ruin'
    | '/settings'
    | '/setup-advisor'
    | '/setup-library'
    | '/signup'
    | '/trade-log'
    | '/weekly-report'
    | '/news/$id'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/chart-analyzer'
    | '/forgot-password'
    | '/game-plan'
    | '/login'
    | '/news'
    | '/onboarding'
    | '/reset-password'
    | '/risk-of-ruin'
    | '/settings'
    | '/setup-advisor'
    | '/setup-library'
    | '/signup'
    | '/trade-log'
    | '/weekly-report'
    | '/news/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ChartAnalyzerRoute: typeof ChartAnalyzerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GamePlanRoute: typeof GamePlanRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RiskOfRuinRoute: typeof RiskOfRuinRoute
  SettingsRoute: typeof SettingsRoute
  SetupAdvisorRoute: typeof SetupAdvisorRoute
  SetupLibraryRoute: typeof SetupLibraryRoute
  SignupRoute: typeof SignupRoute
  TradeLogRoute: typeof TradeLogRoute
  WeeklyReportRoute: typeof WeeklyReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly-report': {
      id: '/weekly-report'
      path: '/weekly-report'
      fullPath: '/weekly-report'
      preLoaderRoute: typeof WeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-log': {
      id: '/trade-log'
      path: '/trade-log'
      fullPath: '/trade-log'
      preLoaderRoute: typeof TradeLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-library': {
      id: '/setup-library'
      path: '/setup-library'
      fullPath: '/setup-library'
      preLoaderRoute: typeof SetupLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-advisor': {
      id: '/setup-advisor'
      path: '/setup-advisor'
      fullPath: '/setup-advisor'
      preLoaderRoute: typeof SetupAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-of-ruin': {
      id: '/risk-of-ruin'
      path: '/risk-of-ruin'
      fullPath: '/risk-of-ruin'
      preLoaderRoute: typeof RiskOfRuinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-plan': {
      id: '/game-plan'
      path: '/game-plan'
      fullPath: '/game-plan'
      preLoaderRoute: typeof GamePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart-analyzer': {
      id: '/chart-analyzer'
      path: '/chart-analyzer'
      fullPath: '/chart-analyzer'
      preLoaderRoute: typeof ChartAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
  }
}

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ChartAnalyzerRoute: ChartAnalyzerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GamePlanRoute: GamePlanRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RiskOfRuinRoute: RiskOfRuinRoute,
  SettingsRoute: SettingsRoute,
  SetupAdvisorRoute: SetupAdvisorRoute,
  SetupLibraryRoute: SetupLibraryRoute,
  SignupRoute: SignupRoute,
  TradeLogRoute: TradeLogRoute,
  WeeklyReportRoute: WeeklyReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
